language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.5.9
  - DJANGO=1.6.7
  - DJANGO=1.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install .
script:
  - python runtests.py